# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bot_builder_entity.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x62ot_builder_entity.proto\x12\x1a\x62ot_builder_entity.service\"&\n\x13GetVariablesRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"O\n\x14GetVariablesResponse\x12\x37\n\tvariables\x18\x01 \x03(\x0b\x32$.bot_builder_entity.service.Variable\"k\n\x08Variable\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tis_system\x18\x03 \x01(\x08\x12\x32\n\x06\x65ntity\x18\x04 \x01(\x0b\x32\".bot_builder_entity.service.Entity\"K\n\x06\x45ntity\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x33\n\x07options\x18\x02 \x03(\x0b\x32\".bot_builder_entity.service.Option\"M\n\x06Option\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x35\n\x08synonyms\x18\x02 \x03(\x0b\x32#.bot_builder_entity.service.Synonym\"\x17\n\x07Synonym\x12\x0c\n\x04name\x18\x01 \x01(\t2\x8b\x01\n\x16\x42otBuilderStoryService\x12q\n\x0cGetVariables\x12/.bot_builder_entity.service.GetVariablesRequest\x1a\x30.bot_builder_entity.service.GetVariablesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bot_builder_entity_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETVARIABLESREQUEST']._serialized_start=56
  _globals['_GETVARIABLESREQUEST']._serialized_end=94
  _globals['_GETVARIABLESRESPONSE']._serialized_start=96
  _globals['_GETVARIABLESRESPONSE']._serialized_end=175
  _globals['_VARIABLE']._serialized_start=177
  _globals['_VARIABLE']._serialized_end=284
  _globals['_ENTITY']._serialized_start=286
  _globals['_ENTITY']._serialized_end=361
  _globals['_OPTION']._serialized_start=363
  _globals['_OPTION']._serialized_end=440
  _globals['_SYNONYM']._serialized_start=442
  _globals['_SYNONYM']._serialized_end=465
  _globals['_BOTBUILDERSTORYSERVICE']._serialized_start=468
  _globals['_BOTBUILDERSTORYSERVICE']._serialized_end=607
# @@protoc_insertion_point(module_scope)
