# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import bot_builder_entity_pb2 as bot__builder__entity__pb2


class BotBuilderStoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEntities = channel.unary_unary(
            "/bot_builder_entity.service.BotBuilderStoryService/GetEntities",
            request_serializer=bot__builder__entity__pb2.GetEntitiesRequest.SerializeToString,
            response_deserializer=bot__builder__entity__pb2.GetEntitiesResponse.FromString,
        )


class BotBuilderStoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEntities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_BotBuilderStoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetEntities": grpc.unary_unary_rpc_method_handler(
            servicer.GetEntities,
            request_deserializer=bot__builder__entity__pb2.GetEntitiesRequest.FromString,
            response_serializer=bot__builder__entity__pb2.GetEntitiesResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "bot_builder_entity.service.BotBuilderStoryService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class BotBuilderStoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEntities(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/bot_builder_entity.service.BotBuilderStoryService/GetEntities",
            bot__builder__entity__pb2.GetEntitiesRequest.SerializeToString,
            bot__builder__entity__pb2.GetEntitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
